// AUTO-GENERATED by scripts/fetch_image_credits.ts from the Wikimedia Commons API.
// Do not edit by hand: change IMAGE_SOURCES in that script and re-run it.

export interface ImageCredit {
  /** Commons file title without the "File:" prefix (or the original file id for other sources) */
  title: string;
  /** Author / required attribution as plain text */
  author: string;
  /** License short name, e.g. "CC BY-SA 4.0" or "Public domain" */
  license: string;
  /** License deed URL (empty for public-domain files) */
  licenseUrl: string;
  /** File description page (Commons) or original URL */
  sourceUrl: string;
  /** Where the image was taken from, e.g. "Wikimedia Commons" */
  sourceName: string;
}

/** Keyed by the site-relative image path used in imageUrl fields. */
export const IMAGE_CREDITS: Record<string, ImageCredit> = {
  "/images/plants/herb-hemp.webp": {
    "title": "Hemp plants-cannabis sativa-single 1.JPG",
    "author": "Nabokov",
    "license": "Public domain",
    "licenseUrl": "",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Hemp_plants-cannabis_sativa-single_1.JPG",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/herb-rhubarb.webp": {
    "title": "Rheum rhabarbarum.2006-04-27.uellue.jpg",
    "author": "Dieter Weber (User:Uellue)",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Rheum_rhabarbarum.2006-04-27.uellue.jpg",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/plant-african-marigold.webp": {
    "title": "Inniswood - Tagetes erecta 1.jpg",
    "author": "Sixflashphoto",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Inniswood_-_Tagetes_erecta_1.jpg",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/plant-albizia.webp": {
    "title": "Albizia chinensis - Chinese Albizia young leaves at Periya 2018 (1).jpg",
    "author": "Vinayaraj",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Albizia_chinensis_-_Chinese_Albizia_young_leaves_at_Periya_2018_(1).jpg",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/plant-alder.webp": {
    "title": "Alnus glutinosa 01 by-dpc.jpg",
    "author": "David Perez",
    "license": "CC BY 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Alnus_glutinosa_01_by-dpc.jpg",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/plant-alfalfa.webp": {
    "title": "75 Medicago sativa L.jpg",
    "author": "Amédée Masclef",
    "license": "Public domain",
    "licenseUrl": "",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:75_Medicago_sativa_L.jpg",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/plant-aster.webp": {
    "title": "Symphyotrichum novae-angliae3.jpg",
    "author": "The Cosmonaut",
    "license": "CC BY-SA 2.5 ca",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.5/ca/deed.en",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Symphyotrichum_novae-angliae3.jpg",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/plant-basil.webp": {
    "title": "Ocimum basilicum CG NBG LR.jpg",
    "author": "PumpkinSky",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Ocimum_basilicum_CG_NBG_LR.jpg",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/plant-blackcurrant.webp": {
    "title": "Ribes nigrum - Cassis à Grez-Doiceau 001.jpg",
    "author": "VerboseDreamer",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Ribes_nigrum_-_Cassis_%C3%A0_Grez-Doiceau_001.jpg",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/plant-blueberry.webp": {
    "title": "Vaccinium corymbosum a2.jpg",
    "author": "Opioła Jerzy (Poland)",
    "license": "CC BY 2.5",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.5",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Vaccinium_corymbosum_a2.jpg",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/plant-borage.webp": {
    "title": "Borago officinalis (2025).jpg",
    "author": "Christian Orlandi",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Borago_officinalis_(2025).jpg",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/plant-buckwheat.webp": {
    "title": "Fagopyrum esculentum kz12.jpg",
    "author": "Krzysztof Ziarnek, Kenraiz",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Fagopyrum_esculentum_kz12.jpg",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/plant-bugleweed.webp": {
    "title": "Ajuga reptans 20070429 132711 1.jpg",
    "author": "G. Edward Johnson",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Ajuga_reptans_20070429_132711_1.jpg",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/plant-catmint.webp": {
    "title": "Nepeta cataria RF.jpg",
    "author": "Robert Flogaus-Faust",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Nepeta_cataria_RF.jpg",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/plant-chamomile.webp": {
    "title": "Matricaria recutita 001.JPG",
    "author": "H. Zell",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Matricaria_recutita_001.JPG",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/plant-chicory.webp": {
    "title": "Cichorium intybus-alvesgaspar1.jpg",
    "author": "Alvesgaspar",
    "license": "CC BY 2.5",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.5",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Cichorium_intybus-alvesgaspar1.jpg",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/plant-chinese-motherwort.webp": {
    "title": "Leonurus japonicus kz02.jpg",
    "author": "Krzysztof Ziarnek, Kenraiz",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Leonurus_japonicus_kz02.jpg",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/plant-chives.webp": {
    "title": "Allium schoenoprasum - Bombus lapidarius - Tootsi.jpg",
    "author": "Ivar Leidus",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Allium_schoenoprasum_-_Bombus_lapidarius_-_Tootsi.jpg",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/plant-comfrey.webp": {
    "title": "Symphytum officinale 01.jpg",
    "author": "Agnieszka Kwiecień (Nova)",
    "license": "CC BY 2.5",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.5",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Symphytum_officinale_01.jpg",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/plant-common-vetch.webp": {
    "title": "Vicia sativa kz05.jpg",
    "author": "Krzysztof Ziarnek, Kenraiz",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Vicia_sativa_kz05.jpg",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/plant-cornflower.webp": {
    "title": "Centaurea cyanus RF.jpg",
    "author": "Robert Flogaus-Faust",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Centaurea_cyanus_RF.jpg",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/plant-cowslip.webp": {
    "title": "Primula veris 0x.JPG",
    "author": "Alvals",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Primula_veris_0x.JPG",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/plant-cranberry.webp": {
    "title": "American Cranberry (Vaccinium macrocarpon) - Tor Bay Provincial Park, Nova Scotia 2022-07-27.jpg",
    "author": "Ryan Hodnett",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:American_Cranberry_(Vaccinium_macrocarpon)_-_Tor_Bay_Provincial_Park,_Nova_Scotia_2022-07-27.jpg",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/plant-creeping-jenny.webp": {
    "title": "Lysimachia nummularia0.jpg",
    "author": "Kurt Stüber",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Lysimachia_nummularia0.jpg",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/plant-creeping-phlox.webp": {
    "title": "Phlox subulata Floks szydlasty 2017-05-01 01.jpg",
    "author": "Agnieszka Kwiecień, Nova",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Phlox_subulata_Floks_szydlasty_2017-05-01_01.jpg",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/plant-crocus.webp": {
    "title": "Crocus vernus with bee.jpg",
    "author": "Generalrelative",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Crocus_vernus_with_bee.jpg",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/plant-daffodil.webp": {
    "title": "Narcissus pseudonarcissus flower 300303.jpg",
    "author": "BerndH",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Narcissus_pseudonarcissus_flower_300303.jpg",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/plant-dandelion.webp": {
    "title": "A Taraxacum Ruderalia dandelion clock.jpg",
    "author": "Richard Bartz, Munich Makro Freak",
    "license": "CC BY-SA 2.5",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.5",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:A_Taraxacum_Ruderalia_dandelion_clock.jpg",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/plant-echinacea.webp": {
    "title": "Echinacea purpurea 001.JPG",
    "author": "H. Zell",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Echinacea_purpurea_001.JPG",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/plant-elaeagnus.webp": {
    "title": "Elaeagnus umbellata1.jpg",
    "author": "KENPEI",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Elaeagnus_umbellata1.jpg",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/plant-elderberry.webp": {
    "title": "Sambucus nigra 004.jpg",
    "author": "Willow",
    "license": "CC BY 2.5",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.5",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Sambucus_nigra_004.jpg",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/plant-epimedium.webp": {
    "title": "Epimedium grandiflorum 1.jpg",
    "author": "Sphl",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Epimedium_grandiflorum_1.jpg",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/plant-fennel.webp": {
    "title": "Foeniculum July 2011-1a.jpg",
    "author": "Alvesgaspar",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Foeniculum_July_2011-1a.jpg",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/plant-fodder-radish.webp": {
    "title": "Bladrammenas groenbemesting Raphanus sativus subsp. oleiferus.jpg",
    "author": "Rasbak",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Bladrammenas_groenbemesting_Raphanus_sativus_subsp._oleiferus.jpg",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/plant-garlic-chives.webp": {
    "title": "Allium tuberosum, 2021-09-05, Beechview, 01.jpg",
    "author": "Cbaile19",
    "license": "CC0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Allium_tuberosum,_2021-09-05,_Beechview,_01.jpg",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/plant-garlic.webp": {
    "title": "Knoblauch Blüte focus stack-20250713-RM-111019.jpg",
    "author": "Reinhold Möller Ermell",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Knoblauch_Bl%C3%BCte_focus_stack-20250713-RM-111019.jpg",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/plant-gliricidia.webp": {
    "title": "Gliricidia sepium (Fabaceae) 01.jpg",
    "author": "Filo gèn'",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Gliricidia_sepium_(Fabaceae)_01.jpg",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/plant-goumi.webp": {
    "title": "Elaeagnus multiflora2.jpg",
    "author": "KENPEI",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Elaeagnus_multiflora2.jpg",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/plant-hellebore.webp": {
    "title": "Helleborus niger Kaiser.jpg",
    "author": "Robert Hundsdorfer",
    "license": "CC BY-SA 2.0 de",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0/de/deed.en",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Helleborus_niger_Kaiser.jpg",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/plant-hemp.webp": {
    "title": "Cannabis sativa plant top view 01.jpg",
    "author": "Jedesto",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Cannabis_sativa_plant_top_view_01.jpg",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/plant-horseradish.webp": {
    "title": "Armoracia rusticana.jpg",
    "author": "Pethan",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Armoracia_rusticana.jpg",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/plant-hosta.webp": {
    "title": "Hosta Bressingham Blue.JPG",
    "author": "Qwertzy2~commonswiki",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Hosta_Bressingham_Blue.JPG",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/plant-hyacinth.webp": {
    "title": "Hyacinthus orientalis 'Delft Blue' 2019-04-06 02.jpg",
    "author": "Agnieszka Kwiecień, Nova",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Hyacinthus_orientalis_%27Delft_Blue%27_2019-04-06_02.jpg",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/plant-hyssop.webp": {
    "title": "Hyssop (Hyssopus officinalis).jpg",
    "author": "K.vliet",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Hyssop_(Hyssopus_officinalis).jpg",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/plant-indian-mustard.webp": {
    "title": "Brassica juncea var. juncea.JPG",
    "author": "Dalgial",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Brassica_juncea_var._juncea.JPG",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/plant-ladys-mantle.webp": {
    "title": "Alchemilla vulgaris with raindrops.jpg",
    "author": "Ansgar Koreng",
    "license": "CC BY-SA 3.0 de",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/de/deed.en",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Alchemilla_vulgaris_with_raindrops.jpg",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/plant-lavender.webp": {
    "title": "Lavandula angustifolia - lavender - Lavendel - 01.jpg",
    "author": "Norbert Nagel",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Lavandula_angustifolia_-_lavender_-_Lavendel_-_01.jpg",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/plant-lemon-balm.webp": {
    "title": "Lemon balm plant.jpg",
    "author": "Amitchell125",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Lemon_balm_plant.jpg",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/plant-linden.webp": {
    "title": "Tilia cordata flowers.jpg",
    "author": "Gmihail at Serbian Wikipedia",
    "license": "CC BY-SA 3.0 rs",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/rs/deed.en",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Tilia_cordata_flowers.jpg",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/plant-lingonberry.webp": {
    "title": "Vaccinium vitis-idaea L..jpg",
    "author": "Carl Axel Magnus Lindman",
    "license": "Public domain",
    "licenseUrl": "",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Vaccinium_vitis-idaea_L..jpg",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/plant-lovage.webp": {
    "title": "Liebstöckel.JPG",
    "author": "4028mdk09",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Liebst%C3%B6ckel.JPG",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/plant-lungwort.webp": {
    "title": "Pulmonaria officinalis (s. str.) sl2.jpg",
    "author": "Stefan.lefnaer",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Pulmonaria_officinalis_(s._str.)_sl2.jpg",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/plant-lupine.webp": {
    "title": "Lupinus perennis in flower.jpg",
    "author": "cassi saari",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Lupinus_perennis_in_flower.jpg",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/plant-marigold.webp": {
    "title": "Tagetes patula 05012015 (3).jpg",
    "author": "Joydeep",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Tagetes_patula_05012015_(3).jpg",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/plant-meadowsweet.webp": {
    "title": "FilipendulaUlmaria.jpg",
    "author": "Christian Fischer",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:FilipendulaUlmaria.jpg",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/plant-miners-lettuce.webp": {
    "title": "Claytonia perfoliata 6641.JPG",
    "author": "Walter Siegmund",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Claytonia_perfoliata_6641.JPG",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/plant-nasturtium.webp": {
    "title": "Tropaeolum majus 2005 G1.jpg",
    "author": "George Chernilevsky",
    "license": "Public domain",
    "licenseUrl": "",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Tropaeolum_majus_2005_G1.jpg",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/plant-nepal-alder.webp": {
    "title": "Alnus nepalensis.JPG",
    "author": "Krish Dulal",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Alnus_nepalensis.JPG",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/plant-nettle.webp": {
    "title": "Brennnessel.jpg",
    "author": "Simplicius",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Brennnessel.jpg",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/plant-oregano.webp": {
    "title": "ORIGANUM VULGARE - SANT JUST - IB-230 (Orenga).JPG",
    "author": "Isidre blanc",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:ORIGANUM_VULGARE_-_SANT_JUST_-_IB-230_(Orenga).JPG",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/plant-ostrich-fern.webp": {
    "title": "Matteuccia struthiopteris fiddleheads.jpg",
    "author": "The Cosmonaut",
    "license": "CC BY-SA 2.5 ca",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.5/ca/deed.en",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Matteuccia_struthiopteris_fiddleheads.jpg",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/plant-peppermint.webp": {
    "title": "Pfefferminze natur peppermint.jpg",
    "author": "Renamed user c97caec71d4b1be7ce73d4a53e2ab940",
    "license": "CC BY 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Pfefferminze_natur_peppermint.jpg",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/plant-phacelia.webp": {
    "title": "Phacelia tanacetifolia (KPFC) 01.jpg",
    "author": "KPFC",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Phacelia_tanacetifolia_(KPFC)_01.jpg",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/plant-pot-marigold.webp": {
    "title": "Ringelblume (Calendula officinalis) Blüte focus stack-20220619-RM-165610.jpg",
    "author": "Ermell",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Ringelblume_(Calendula_officinalis)_Bl%C3%BCte_focus_stack-20220619-RM-165610.jpg",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/plant-red-currant.webp": {
    "title": "Ribes rubrum 1.jpg",
    "author": "Thue",
    "license": "Public domain",
    "licenseUrl": "",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Ribes_rubrum_1.jpg",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/plant-rhododendron.webp": {
    "title": "Rhododendron-catawbiense.jpg",
    "author": "Edgester",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Rhododendron-catawbiense.jpg",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/plant-rhubarb.webp": {
    "title": "Rheum rhabarbarum.2006-04-27.uellue.jpg",
    "author": "Dieter Weber (User:Uellue)",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Rheum_rhabarbarum.2006-04-27.uellue.jpg",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/plant-ribwort-plantain.webp": {
    "title": "Plantago lanceolata kz09.jpg",
    "author": "Krzysztof Ziarnek, Kenraiz",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Plantago_lanceolata_kz09.jpg",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/plant-rosemary.webp": {
    "title": "Rosemary in bloom.JPG",
    "author": "Margalob",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Rosemary_in_bloom.JPG",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/plant-sage.webp": {
    "title": "Salvia officinalis in Cardaillac (1).jpg",
    "author": "Krzysztof Golik",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Salvia_officinalis_in_Cardaillac_(1).jpg",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/plant-sainfoin.webp": {
    "title": "Onobrychis viciifolia Inflorescence 11April2009 CampoCalatrava.jpg",
    "author": "javier martin",
    "license": "Public domain",
    "licenseUrl": "",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Onobrychis_viciifolia_Inflorescence_11April2009_CampoCalatrava.jpg",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/plant-salad-burnet.webp": {
    "title": "Sanguisorba minor (female flowers).jpg",
    "author": "Hans Hillewaert",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Sanguisorba_minor_(female_flowers).jpg",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/plant-seabuckthorn.webp": {
    "title": "Hippophae rhamnoides-01 (xndr).JPG",
    "author": "Svdmolen",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Hippophae_rhamnoides-01_(xndr).JPG",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/plant-sedum.webp": {
    "title": "Sedum spectabile - blossom top (aka).jpg",
    "author": "André Karwath aka Aka",
    "license": "CC BY-SA 2.5",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.5",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Sedum_spectabile_-_blossom_top_(aka).jpg",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/plant-sicklepod.webp": {
    "title": "Senna tora Blanco1.122-cropped.jpg",
    "author": "Francisco Manuel Blanco (O.S.A.)",
    "license": "Public domain",
    "licenseUrl": "",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Senna_tora_Blanco1.122-cropped.jpg",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/plant-snowdrop.webp": {
    "title": "Galanthus nivalis.jpg",
    "author": "Caroig",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Galanthus_nivalis.jpg",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/plant-sorghum-sudangrass.webp": {
    "title": "Sudangras,Sudan grass,-Sorghum bicolor (L.) Moench nothosubsp. drummondii (Steud.) de Wet ex Davidse-.jpg",
    "author": "Daniel Georg Döhne",
    "license": "CC BY 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Sudangras,Sudan_grass,-Sorghum_bicolor_(L.)_Moench_nothosubsp._drummondii_(Steud.)_de_Wet_ex_Davidse-.jpg",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/plant-southernwood.webp": {
    "title": "Artemisia abrotanum0.jpg",
    "author": "Kurt Stüber",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Artemisia_abrotanum0.jpg",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/plant-soybean.webp": {
    "title": "Soybean.USDA.jpg",
    "author": "U.S. Department of Agriculture",
    "license": "Public domain",
    "licenseUrl": "",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Soybean.USDA.jpg",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/plant-strawberry.webp": {
    "title": "Fragaria vesca - metsmaasikas.jpg",
    "author": "Ivar Leidus",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Fragaria_vesca_-_metsmaasikas.jpg",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/plant-subterranean-clover.webp": {
    "title": "Trifolium subterraneum (flowers).jpg",
    "author": "Hans Hillewaert",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Trifolium_subterraneum_(flowers).jpg",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/plant-summer-savory.webp": {
    "title": "Satureja hortensis, Insektenbesuch, Josef Schlaghecken.jpg",
    "author": "Josef Schlaghecken",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Satureja_hortensis,_Insektenbesuch,_Josef_Schlaghecken.jpg",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/plant-sweet-alyssum.webp": {
    "title": "Smagliczka nadmorska 1.jpg",
    "author": "w0zny",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Smagliczka_nadmorska_1.jpg",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/plant-sweet-cicely.webp": {
    "title": "Myrrhis odorata, Roomse kervel plant.jpg",
    "author": "Rasbak",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Myrrhis_odorata,_Roomse_kervel_plant.jpg",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/plant-sweet-flag.webp": {
    "title": "AcorusCalamus.jpg",
    "author": "Christian Fischer",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:AcorusCalamus.jpg",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/plant-sweet-potato.webp": {
    "title": "Ipomoea batatas 006.JPG",
    "author": "Llez",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Ipomoea_batatas_006.JPG",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/plant-tansy.webp": {
    "title": "20140711Tanacetum vulgare.jpg",
    "author": "AnRo0002",
    "license": "CC0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:20140711Tanacetum_vulgare.jpg",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/plant-tea-sinensis.webp": {
    "title": "Tea, two leaves and a bud.jpg",
    "author": "Nborkakoty at English Wikipedia",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Tea,_two_leaves_and_a_bud.jpg",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/plant-thyme.webp": {
    "title": "Thymus serpyllum1.jpg",
    "author": "Rasbak",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Thymus_serpyllum1.jpg",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/plant-tithonia.webp": {
    "title": "Tithonia diversifolia I.jpg",
    "author": "Rjcastillo",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Tithonia_diversifolia_I.jpg",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/plant-welsh-onion.webp": {
    "title": "Negibozu 06x1963sv.jpg",
    "author": "Cory",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Negibozu_06x1963sv.jpg",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/plant-white-clover.webp": {
    "title": "Trifolium repens - white clover on way from Govindghat to Gangria at Valley of Flowers National Park - during LGFC - VOF 2019 (1).jpg",
    "author": "Vinayaraj",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Trifolium_repens_-_white_clover_on_way_from_Govindghat_to_Gangria_at_Valley_of_Flowers_National_Park_-_during_LGFC_-_VOF_2019_(1).jpg",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/plant-wild-carrot.webp": {
    "title": "Daucus carota May 2008-1 edit.jpg",
    "author": "Alvesgaspar",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Daucus_carota_May_2008-1_edit.jpg",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/plant-wild-garlic.webp": {
    "title": "Photo of Allium Ursinum, wild garlic, north-west Hampshire, UK, May 2014.jpg",
    "author": "Rodolph at English Wikipedia",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Photo_of_Allium_Ursinum,_wild_garlic,_north-west_Hampshire,_UK,_May_2014.jpg",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/plant-wild-ginger.webp": {
    "title": "Asarum europaeum 170406.jpg",
    "author": "Bernd Haynold",
    "license": "CC BY 2.5",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.5",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Asarum_europaeum_170406.jpg",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/plant-willow.webp": {
    "title": "Salix viminalis 001.jpg",
    "author": "Willow",
    "license": "CC BY-SA 2.5",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.5",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Salix_viminalis_001.jpg",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/plant-winter-aconite.webp": {
    "title": "Winterling-Bluete-70.jpg",
    "author": "Gaucho~commonswiki",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Winterling-Bluete-70.jpg",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/plant-wintergreen.webp": {
    "title": "Gaultheria procumbens Golteria rozesłana 2020-08-07 04.jpg",
    "author": "Agnieszka Kwiecień, Nova",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Gaultheria_procumbens_Golteria_rozes%C5%82ana_2020-08-07_04.jpg",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/plant-woodruff.webp": {
    "title": "Waldmeister(Mai).JPG",
    "author": "Hajotthu",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Waldmeister(Mai).JPG",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/plant-wormwood.webp": {
    "title": "Artemisia absinthium P1210748.jpg",
    "author": "David Monniaux",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Artemisia_absinthium_P1210748.jpg",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/plant-yarrow.webp": {
    "title": "Achillea millefolium (bright).jpg",
    "author": "SAplants",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Achillea_millefolium_(bright).jpg",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/shrub-blackcurrant.webp": {
    "title": "Ribes nigrum - Cassis à Grez-Doiceau 001.jpg",
    "author": "VerboseDreamer",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Ribes_nigrum_-_Cassis_%C3%A0_Grez-Doiceau_001.jpg",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/shrub-blueberry.webp": {
    "title": "Vaccinium corymbosum a2.jpg",
    "author": "Opioła Jerzy (Poland)",
    "license": "CC BY 2.5",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.5",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Vaccinium_corymbosum_a2.jpg",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/shrub-elderberry.webp": {
    "title": "00 3769 Schwarzen Holunder (Sambucus nigra).jpg",
    "author": "W. Bulach",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:00_3769_Schwarzen_Holunder_(Sambucus_nigra).jpg",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/shrub-red-currant.webp": {
    "title": "Ribes rubrum 1.jpg",
    "author": "Thue",
    "license": "Public domain",
    "licenseUrl": "",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Ribes_rubrum_1.jpg",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/shrub-rhododendron.webp": {
    "title": "Rhododendron-catawbiense.jpg",
    "author": "Edgester",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Rhododendron-catawbiense.jpg",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/tree-alder.webp": {
    "title": "Alnus glutinosa 01 by-dpc.jpg",
    "author": "David Perez",
    "license": "CC BY 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Alnus_glutinosa_01_by-dpc.jpg",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/tree-apple.webp": {
    "title": "Apples on tree 2021 G2.jpg",
    "author": "George Chernilevsky",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Apples_on_tree_2021_G2.jpg",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/tree-apricot.webp": {
    "title": "Apricots.jpg",
    "author": "Fir0002",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Apricots.jpg",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/tree-cherry.webp": {
    "title": "Cherries on a tree Germany 2020.jpg",
    "author": "NiTenIchiRyu",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Cherries_on_a_tree_Germany_2020.jpg",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/tree-chestnut.webp": {
    "title": "Frucht der Edelkastanie.jpg",
    "author": "Benjamin Gimmel, BenHur",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Frucht_der_Edelkastanie.jpg",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/tree-fig.webp": {
    "title": "Figs.jpg",
    "author": "Eric Hunt",
    "license": "CC BY-SA 2.5",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.5",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Figs.jpg",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/tree-ginkgo.webp": {
    "title": "GinkgoLeaves.jpg",
    "author": "Joe Schneid, Louisville, Kentucky",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:GinkgoLeaves.jpg",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/tree-hazelnut.webp": {
    "title": "Corylus avellana (Betulaceae) - (fruit-bearing), Elst (Gld), the Netherlands.jpg",
    "author": "B. Schoenmakers (Waarneming.nl)",
    "license": "CC BY 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Corylus_avellana_(Betulaceae)_-_(fruit-bearing),_Elst_(Gld),_the_Netherlands.jpg",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/tree-linden.webp": {
    "title": "Tilia cordata flowers.jpg",
    "author": "Gmihail at Serbian Wikipedia",
    "license": "CC BY-SA 3.0 rs",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/rs/deed.en",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Tilia_cordata_flowers.jpg",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/tree-mulberry.webp": {
    "title": "Ripe fruit of morus nigra.JPG",
    "author": "Miloslav Bahna",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Ripe_fruit_of_morus_nigra.JPG",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/tree-pawpaw.webp": {
    "title": "Asimina triloba3.jpg",
    "author": "Scott Bauer, USDA",
    "license": "Public domain",
    "licenseUrl": "",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Asimina_triloba3.jpg",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/tree-peach.webp": {
    "title": "Prunus persica-Jerusalem-Fruits.jpg",
    "author": "Yair Haklai",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Prunus_persica-Jerusalem-Fruits.jpg",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/tree-pear.webp": {
    "title": "Conference-Birnen.jpg",
    "author": "User:MarkusHagenlocher",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Conference-Birnen.jpg",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/tree-plum.webp": {
    "title": "Fruits Prunus domestica.jpg",
    "author": "YAMAMAYA",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Fruits_Prunus_domestica.jpg",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/tree-quince.webp": {
    "title": "2022-09-11 Birnenquitte.jpg",
    "author": "Bärbel Miemietz",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:2022-09-11_Birnenquitte.jpg",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/tree-seabuckthorn-star.webp": {
    "title": "Hippophae rhamnoides-01 (xndr).JPG",
    "author": "Svdmolen",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Hippophae_rhamnoides-01_(xndr).JPG",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/tree-tea-assamica.webp": {
    "title": "Camellia sinensis var. assamica in Auckland Botanic Gardens.jpg",
    "author": "Krzysztof Golik",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Camellia_sinensis_var._assamica_in_Auckland_Botanic_Gardens.jpg",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/tree-tea-sinensis.webp": {
    "title": "Csinensis.jpg",
    "author": "AxelBoldt at en.wikipedia",
    "license": "Public domain",
    "licenseUrl": "",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Csinensis.jpg",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/tree-walnut.webp": {
    "title": "Black Walnut nut and leave detail.JPG",
    "author": "MONGO",
    "license": "Public domain",
    "licenseUrl": "",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Black_Walnut_nut_and_leave_detail.JPG",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/vine-grape.webp": {
    "title": "Uva nera da vino - grappoli 1.jpg",
    "author": "Anna.Massini",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Uva_nera_da_vino_-_grappoli_1.jpg",
    "sourceName": "Wikimedia Commons"
  },
  "/images/plants/vine-kiwi.webp": {
    "title": "2015-09-27 Kiwi Beeren aus Österreich.JPG",
    "author": "Kontrollstellekundl",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:2015-09-27_Kiwi_Beeren_aus_%C3%96sterreich.JPG",
    "sourceName": "Wikimedia Commons"
  },
  "/images/soils/soil-acidic.webp": {
    "title": "Pine forest floor, Jamestown Island, 2014-03-19, 01.jpg",
    "author": "Cbaile19",
    "license": "CC0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Pine_forest_floor,_Jamestown_Island,_2014-03-19,_01.jpg",
    "sourceName": "Wikimedia Commons"
  },
  "/images/soils/soil-chalky.webp": {
    "title": "Calcareous Soil Profile, Seven Sisters Country Park - geograph.org.uk - 1280181.jpg",
    "author": "Nigel Chadwick",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Calcareous_Soil_Profile,_Seven_Sisters_Country_Park_-_geograph.org.uk_-_1280181.jpg",
    "sourceName": "Wikimedia Commons"
  },
  "/images/soils/soil-clay.webp": {
    "title": "Cracked mud in Black Rock desert.JPG",
    "author": "Jcomeau ictx",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Cracked_mud_in_Black_Rock_desert.JPG",
    "sourceName": "Wikimedia Commons"
  },
  "/images/soils/soil-loam.webp": {
    "title": "Earth pattern.jpg",
    "author": "Titus Tscharntke",
    "license": "Public domain",
    "licenseUrl": "",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Earth_pattern.jpg",
    "sourceName": "Wikimedia Commons"
  },
  "/images/soils/soil-sandy.webp": {
    "title": "Yellow sand texture.jpg",
    "author": "Titus Tscharntke",
    "license": "Public domain",
    "licenseUrl": "",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Yellow_sand_texture.jpg",
    "sourceName": "Wikimedia Commons"
  },
  "/images/soils/soil-silt.webp": {
    "title": "Loess (9940595213).jpg",
    "author": "Oregon Caves from Cave Junction, USA",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Loess_(9940595213).jpg",
    "sourceName": "Wikimedia Commons"
  }
};

/** Looks up the credit for an imageUrl (query strings such as ?v=4 are ignored). */
export const getImageCredit = (imageUrl: string | undefined): ImageCredit | undefined =>
  imageUrl ? IMAGE_CREDITS[imageUrl.split(/[?#]/)[0]] : undefined;
